# -*- coding: utf-8 -*-
"""Matdis_Owid_Covid19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MGnqr8uIyYl7EMK9NkldvDLLTS53G-Au
"""
#%%
## Import Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import pyplot
from sklearn.metrics import mean_squared_error

## Load csv file
data = pd.read_csv(r"D:\Universitas Pembangunan Jaya\Semester 3\Matematika Diskrit\owid-covid-data.csv")

print(data.head())

## Definisikan negara-negara
indo=data.query('iso_code == "IDN"')
spain=data.query('iso_code == "ESP"')
german=data.query('iso_code == "DEU"')
argentina=data.query('iso_code == "ARG"')

## gunakan plot untuk menampilkan data
sns.lineplot(data=indo,x='date',y='total_deaths')
sns.lineplot(data=spain,x='date',y='total_deaths')
sns.lineplot(data=german,x='date',y='total_deaths')
sns.lineplot(data=argentina,x='date',y='total_deaths')
plt.xticks([0,100,200,300,400,500], rotation=45)
plt.legend(['Indonesia', 'Spanyol', 'German', 'Argentina'])
plt.show()

## Definisikan Negara mulai dari tanggal 1 mei sampai hari ini
indo2      = indo.query('date >= "2021-05-01"')
spain2     = spain.query('date >= "2021-05-01"')
german2    = german.query('date >= "2021-05-01"')
argentina2 = argentina.query('date >= "2021-05-01"')

## gunakan plot untuk menampilkan data
sns.lineplot(data=indo2,x='date',y='total_deaths')
sns.lineplot(data=spain2,x='date',y='total_deaths')
sns.lineplot(data=german2,x='date',y='total_deaths')
sns.lineplot(data=argentina2,x='date',y='total_deaths')
plt.xticks([0,30,60,90,120,150], rotation=45)
plt.legend(['Indonesia', 'Spanyol', 'German', 'Argentina'])
plt.show()
# %%
